load("//bazel:rules/react/defs.bzl", "react_app")


NPM_DEPS = [
    "//:node_modules/eslint-config-react-app",
    "//:node_modules/react-dom",
    "//:node_modules/react-scripts",
    "//:node_modules/react",
    "//:node_modules/typescript",
    "//:node_modules/web-vitals",
]

react_app(npm_deps = NPM_DEPS)


